# Use root/example as user/password credentials
version: '3.1'

services:

  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8000:8000
  
  elk:
    image: sebp/elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes